language: csharp
solution: Reducto.sln
install:
    - nuget restore Reducto.sln
    - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release Reducto.sln
    - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Reducto.Tests/bin/Release/Reducto.Tests.dll